import os
params = env['ir.config_parameter'].sudo()
params.set_str('report.url', 'http://odoo:8069')
params.set_str('web.base.url', 'http://localhost:8070')
params.set_str('web.base.url.freeze', 'True')
params.set_str('report.pdf_engine_default', 'wkhtmltopdf')
admin = env.ref('base.user_admin')
admin.write({'login': 'admin', 'password': os.environ['ODOO_ADMIN_PASSWORD']})
env.company.write({'name': 'Myanmar Unicode Demo', 'report_footer': 'Odoo 20 · Myanmar Unicode PDF demo'})
env.cr.commit()
print('Myanmar demo initialized')
